package entity;
// Generated Apr 10, 2020 12:57:32 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name="customers"
    ,catalog="salelaptopmanagement"
)
public class Customers  implements java.io.Serializable {


     private String customerId;
     private String name;
     private String phoneNumber;
     private String address;
     private String email;
     private String identificationNumber;
     private Date dateOfBirth;
     private String profilePicture;
     private String userName;
     private String password;
     private boolean adminPermission;
     private Set<Receipts> receiptses = new HashSet<Receipts>(0);

    public Customers() {
    }

	
    public Customers(String customerId, String name, String phoneNumber, String address, String identificationNumber, String userName, String password, boolean adminPermission) {
        this.customerId = customerId;
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.address = address;
        this.identificationNumber = identificationNumber;
        this.userName = userName;
        this.password = password;
        this.adminPermission = adminPermission;
    }
    public Customers(String customerId, String name, String phoneNumber, String address, String email, String identificationNumber, Date dateOfBirth, String profilePicture, String userName, String password, boolean adminPermission, Set<Receipts> receiptses) {
       this.customerId = customerId;
       this.name = name;
       this.phoneNumber = phoneNumber;
       this.address = address;
       this.email = email;
       this.identificationNumber = identificationNumber;
       this.dateOfBirth = dateOfBirth;
       this.profilePicture = profilePicture;
       this.userName = userName;
       this.password = password;
       this.adminPermission = adminPermission;
       this.receiptses = receiptses;
    }
   
     @Id 

    
    @Column(name="Customer_ID", unique=true, nullable=false, length=10)
    public String getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="Name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Phone_Number", nullable=false, length=50)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="Address", nullable=false, length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="Email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Identification_Number", nullable=false, length=20)
    public String getIdentificationNumber() {
        return this.identificationNumber;
    }
    
    public void setIdentificationNumber(String identificationNumber) {
        this.identificationNumber = identificationNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date_Of_Birth", length=10)
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    
    @Column(name="Profile_Picture", length=100)
    public String getProfilePicture() {
        return this.profilePicture;
    }
    
    public void setProfilePicture(String profilePicture) {
        this.profilePicture = profilePicture;
    }

    
    @Column(name="UserName", nullable=false, length=50)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="PASSWORD", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="Admin_Permission", nullable=false)
    public boolean isAdminPermission() {
        return this.adminPermission;
    }
    
    public void setAdminPermission(boolean adminPermission) {
        this.adminPermission = adminPermission;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customers")
    public Set<Receipts> getReceiptses() {
        return this.receiptses;
    }
    
    public void setReceiptses(Set<Receipts> receiptses) {
        this.receiptses = receiptses;
    }




}


