package entity;
// Generated Apr 10, 2020 12:57:32 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ReceiptDetails generated by hbm2java
 */
@Entity
@Table(name="receipt_details"
    ,catalog="salelaptopmanagement"
)
public class ReceiptDetails  implements java.io.Serializable {


     private String receiptDetailId;
     private Products products;
     private Receipts receipts;
     private int quantity;

    public ReceiptDetails() {
    }

    public ReceiptDetails(String receiptDetailId, Products products, Receipts receipts, int quantity) {
       this.receiptDetailId = receiptDetailId;
       this.products = products;
       this.receipts = receipts;
       this.quantity = quantity;
    }
   
     @Id 

    
    @Column(name="Receipt_Detail_ID", unique=true, nullable=false, length=10)
    public String getReceiptDetailId() {
        return this.receiptDetailId;
    }
    
    public void setReceiptDetailId(String receiptDetailId) {
        this.receiptDetailId = receiptDetailId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Product_ID", nullable=false)
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Receipt_ID", nullable=false)
    public Receipts getReceipts() {
        return this.receipts;
    }
    
    public void setReceipts(Receipts receipts) {
        this.receipts = receipts;
    }

    
    @Column(name="Quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


