package entity;
// Generated Apr 10, 2020 12:57:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Suppliers generated by hbm2java
 */
@Entity
@Table(name="suppliers"
    ,catalog="salelaptopmanagement"
)
public class Suppliers  implements java.io.Serializable {


     private String supplierId;
     private String supplierName;
     private String address;
     private String phoneNumber;
     private Set<Products> productses = new HashSet<Products>(0);

    public Suppliers() {
    }

	
    public Suppliers(String supplierId, String supplierName) {
        this.supplierId = supplierId;
        this.supplierName = supplierName;
    }
    public Suppliers(String supplierId, String supplierName, String address, String phoneNumber, Set<Products> productses) {
       this.supplierId = supplierId;
       this.supplierName = supplierName;
       this.address = address;
       this.phoneNumber = phoneNumber;
       this.productses = productses;
    }
   
     @Id 

    
    @Column(name="Supplier_ID", unique=true, nullable=false, length=10)
    public String getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId;
    }

    
    @Column(name="Supplier_Name", nullable=false, length=50)
    public String getSupplierName() {
        return this.supplierName;
    }
    
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    
    @Column(name="Address", length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="Phone_Number", length=20)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="suppliers")
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }




}


