package entity;
// Generated Apr 10, 2020 12:57:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="products"
    ,catalog="salelaptopmanagement"
)
public class Products  implements java.io.Serializable {


     private String productId;
     private Suppliers suppliers;
     private String name;
     private String brand;
     private String image;
     private Integer price;
     private String modelCode;
     private String size;
     private Integer weight;
     private String color;
     private String networkCommunication;
     private String processor;
     private String processorSpeed;
     private String operatingSystem;
     private String screenSize;
     private String resolution;
     private String screenType;
     private String vga;
     private String vgaMemory;
     private String hardDriveCapacity;
     private String disc;
     private String ramMemory;
     private String ramGen;
     private String bus;
     private String camera;
     private String port;
     private String battery;
     private Set<ReceiptDetails> receiptDetailses = new HashSet<ReceiptDetails>(0);

    public Products() {
    }

	
    public Products(String productId, Suppliers suppliers, String name, String brand) {
        this.productId = productId;
        this.suppliers = suppliers;
        this.name = name;
        this.brand = brand;
    }
    public Products(String productId, Suppliers suppliers, String name, String brand, String image, Integer price, String modelCode, String size, Integer weight, String color, String networkCommunication, String processor, String processorSpeed, String operatingSystem, String screenSize, String resolution, String screenType, String vga, String vgaMemory, String hardDriveCapacity, String disc, String ramMemory, String ramGen, String bus, String camera, String port, String battery, Set<ReceiptDetails> receiptDetailses) {
       this.productId = productId;
       this.suppliers = suppliers;
       this.name = name;
       this.brand = brand;
       this.image = image;
       this.price = price;
       this.modelCode = modelCode;
       this.size = size;
       this.weight = weight;
       this.color = color;
       this.networkCommunication = networkCommunication;
       this.processor = processor;
       this.processorSpeed = processorSpeed;
       this.operatingSystem = operatingSystem;
       this.screenSize = screenSize;
       this.resolution = resolution;
       this.screenType = screenType;
       this.vga = vga;
       this.vgaMemory = vgaMemory;
       this.hardDriveCapacity = hardDriveCapacity;
       this.disc = disc;
       this.ramMemory = ramMemory;
       this.ramGen = ramGen;
       this.bus = bus;
       this.camera = camera;
       this.port = port;
       this.battery = battery;
       this.receiptDetailses = receiptDetailses;
    }
   
     @Id 

    
    @Column(name="Product_ID", unique=true, nullable=false, length=10)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Supplier_ID", nullable=false)
    public Suppliers getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Suppliers suppliers) {
        this.suppliers = suppliers;
    }

    
    @Column(name="Name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Brand", nullable=false, length=50)
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }

    
    @Column(name="Image", length=100)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    
    @Column(name="Price")
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }

    
    @Column(name="Model_Code", length=50)
    public String getModelCode() {
        return this.modelCode;
    }
    
    public void setModelCode(String modelCode) {
        this.modelCode = modelCode;
    }

    
    @Column(name="Size", length=50)
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }

    
    @Column(name="Weight")
    public Integer getWeight() {
        return this.weight;
    }
    
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    
    @Column(name="Color", length=10)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }

    
    @Column(name="Network_Communication", length=50)
    public String getNetworkCommunication() {
        return this.networkCommunication;
    }
    
    public void setNetworkCommunication(String networkCommunication) {
        this.networkCommunication = networkCommunication;
    }

    
    @Column(name="Processor", length=50)
    public String getProcessor() {
        return this.processor;
    }
    
    public void setProcessor(String processor) {
        this.processor = processor;
    }

    
    @Column(name="Processor_Speed", length=50)
    public String getProcessorSpeed() {
        return this.processorSpeed;
    }
    
    public void setProcessorSpeed(String processorSpeed) {
        this.processorSpeed = processorSpeed;
    }

    
    @Column(name="Operating_System", length=50)
    public String getOperatingSystem() {
        return this.operatingSystem;
    }
    
    public void setOperatingSystem(String operatingSystem) {
        this.operatingSystem = operatingSystem;
    }

    
    @Column(name="Screen_Size", length=50)
    public String getScreenSize() {
        return this.screenSize;
    }
    
    public void setScreenSize(String screenSize) {
        this.screenSize = screenSize;
    }

    
    @Column(name="Resolution", length=50)
    public String getResolution() {
        return this.resolution;
    }
    
    public void setResolution(String resolution) {
        this.resolution = resolution;
    }

    
    @Column(name="Screen_Type", length=50)
    public String getScreenType() {
        return this.screenType;
    }
    
    public void setScreenType(String screenType) {
        this.screenType = screenType;
    }

    
    @Column(name="VGA", length=50)
    public String getVga() {
        return this.vga;
    }
    
    public void setVga(String vga) {
        this.vga = vga;
    }

    
    @Column(name="VGA_Memory", length=50)
    public String getVgaMemory() {
        return this.vgaMemory;
    }
    
    public void setVgaMemory(String vgaMemory) {
        this.vgaMemory = vgaMemory;
    }

    
    @Column(name="Hard_Drive_Capacity", length=50)
    public String getHardDriveCapacity() {
        return this.hardDriveCapacity;
    }
    
    public void setHardDriveCapacity(String hardDriveCapacity) {
        this.hardDriveCapacity = hardDriveCapacity;
    }

    
    @Column(name="Disc", length=50)
    public String getDisc() {
        return this.disc;
    }
    
    public void setDisc(String disc) {
        this.disc = disc;
    }

    
    @Column(name="Ram_Memory", length=50)
    public String getRamMemory() {
        return this.ramMemory;
    }
    
    public void setRamMemory(String ramMemory) {
        this.ramMemory = ramMemory;
    }

    
    @Column(name="Ram_Gen", length=50)
    public String getRamGen() {
        return this.ramGen;
    }
    
    public void setRamGen(String ramGen) {
        this.ramGen = ramGen;
    }

    
    @Column(name="BUS", length=50)
    public String getBus() {
        return this.bus;
    }
    
    public void setBus(String bus) {
        this.bus = bus;
    }

    
    @Column(name="Camera", length=50)
    public String getCamera() {
        return this.camera;
    }
    
    public void setCamera(String camera) {
        this.camera = camera;
    }

    
    @Column(name="Port", length=100)
    public String getPort() {
        return this.port;
    }
    
    public void setPort(String port) {
        this.port = port;
    }

    
    @Column(name="Battery", length=50)
    public String getBattery() {
        return this.battery;
    }
    
    public void setBattery(String battery) {
        this.battery = battery;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="products")
    public Set<ReceiptDetails> getReceiptDetailses() {
        return this.receiptDetailses;
    }
    
    public void setReceiptDetailses(Set<ReceiptDetails> receiptDetailses) {
        this.receiptDetailses = receiptDetailses;
    }




}


