package entity;
// Generated Apr 10, 2020 12:57:32 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Receipts generated by hbm2java
 */
@Entity
@Table(name="receipts"
    ,catalog="salelaptopmanagement"
)
public class Receipts  implements java.io.Serializable {


     private String receiptId;
     private Customers customers;
     private Date transactionDay;
     private Integer total;
     private Set<ReceiptDetails> receiptDetailses = new HashSet<ReceiptDetails>(0);

    public Receipts() {
    }

	
    public Receipts(String receiptId, Customers customers, Date transactionDay) {
        this.receiptId = receiptId;
        this.customers = customers;
        this.transactionDay = transactionDay;
    }
    public Receipts(String receiptId, Customers customers, Date transactionDay, Integer total, Set<ReceiptDetails> receiptDetailses) {
       this.receiptId = receiptId;
       this.customers = customers;
       this.transactionDay = transactionDay;
       this.total = total;
       this.receiptDetailses = receiptDetailses;
    }
   
     @Id 

    
    @Column(name="Receipt_ID", unique=true, nullable=false, length=10)
    public String getReceiptId() {
        return this.receiptId;
    }
    
    public void setReceiptId(String receiptId) {
        this.receiptId = receiptId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_ID", nullable=false)
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Day", nullable=false, length=10)
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    public Date getTransactionDay() {
        return this.transactionDay;
    }
    
    public void setTransactionDay(Date transactionDay) {
        this.transactionDay = transactionDay;
    }

    
    @Column(name="Total")
    public Integer getTotal() {
        return this.total;
    }
    
    public void setTotal(Integer total) {
        this.total = total;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="receipts")
    public Set<ReceiptDetails> getReceiptDetailses() {
        return this.receiptDetailses;
    }
    
    public void setReceiptDetailses(Set<ReceiptDetails> receiptDetailses) {
        this.receiptDetailses = receiptDetailses;
    }




}


